a: main.o pdp11.o run.o funcs.o
	gcc -o a main.o pdp11.o run.o funcs.o

main.o: main.c
	gcc -c main.c
pdp11.o: pdp11.c
	gcc -c pdp11.c
run.o: run.c
	gcc -c run.c
funcs.o: funcs.c
	gcc -c funcs.c
